### ISSUE TITLE
Domain Proxy backend support for CBSD deregister and state reset

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#169]
Currently we have no option to have AMC ignore a CBSD and have its state deregistered in SAS (But still have the cbsd in domain proxy database)

Design Doc: https://docs.google.com/document/d/1Iyv0bdWirbfIzhzPBAQjlkYmuwEy-FhksLj6IwshDEg/edit#

**Comment by xbend** [comment]
Check if CBSD desired state deregistration is supported by Backend API (can we change active mode config per CBSD to set desired state to DEREGISTER)

FYI @jkmar

**Comment by xbend** [comment]
Our current backend doesn't have support for CBSD deregister (aka, editing active mode config).
This task still needs to be done/implemented.

**Comment by xbend** [comment]
This issue was discussed during standup meeting on 23.03.2022.
The deregistration usecase is complex, as this action can interfere with other actions in Domain Proxy.

We would need to analyze it based on requirements what are the expected behaviors in different scenarios - based on a requirement/design document.
