### ISSUE TITLE
Support for Active and Pasive modes

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#24]
DP Requirement ID: **APM-01**

The aggregation and proxy management process shall support two modes of operation including Active and Passive.

**Comment by xbend** [comment]
A few things need to be clarifited to fully end this task:

- With the addition of active mode controller, we lost the full passive mode support because of DP changes in database schema relations. Passive mode will currently only work for a scenario where first communication from a radio is a registration request (which will create the cbsd entity in db)
We need to figure out when and how we should create sbsd entities in db on situations, where DP will "intercept" a CBSD-SAS communication "in the middle" (for example the first request from a radio is a grant request)

- Active/Passive setting can be set in multiple layers:
* Global service setting
* Per cbsd setting
We need to establish the setting priorities

**Comment by xbend** [comment]
This task will be treated as "requirements specification", and once all the points have been cleared, implementation tasks will be created.
